### ISSUE TITLE
Oracle: make number of max open cursors exceeded

### ISSUE THREAD

**Issue by jdonnerstag** [sue445/plant_erd#224]
When running the tool against our Oracle database, we receive an "ORA-01000: maximum open cursors exceeded" (300 in our Oracle config). I couldn't find an option to configure the max open cursor count in plant_erd, which I would prefer. Alternatively I need to talk to the DB admins to extend the Oracle DB limit. 

Any idea what determines the number of open cursors?

thanks a lot for your help

**Comment by sue445** [comment]
@jdonnerstag Sorry, I don't use Oracle much, so fixing bugs is difficult for me.

If you could send me a patch I will review and merge.

**Comment by jdonnerstag** [comment]
I would love to, but I have no go-lang knowledge. May be you can help me with pointers where to look at in the source code. E.g. I'm not convinced it is an Oracle issue, but rather how the application works in general (also for other databases). Multiple cursors means, that multiple SQL queries are executed in parallel sessions. Something like, plant_erd retrieves the list of tables, and then executes an SQL command on each table (in parallel). And if the number of tables exceeds a (Oracle) limit, the db will raise an error. Something like this might happen. Any idea where to start searching in the source code?

**Comment by javedashraf** [comment]
After analysis, we found that adding **stmt.Close()** to the adapter.go files for Oracle, the open cursor issues were resolved. 

We additionally found that the foreign key relationship were not created in the ERD files because the Table names from Oracle were in Capital letters and the **tableNames.Contains(foreignKey.ToTable)** statement in schema.go returns no results. A conversion to lower case before doing the Contains check resolved the problem.

I will create a Pull request with these 2 changes and you can check them. Thanks!

**Comment by sue445** [comment]
This issue was resolved at #225

**Comment by sue445** [comment]
I published as `v0.4.4` 🚀 
https://github.com/sue445/plant_erd/blob/master/CHANGELOG.md#v044
